let value = document.getElementById("wish");
console.log(pen);
let mouse = document.getElementsByClassName("wishes");
console.log(mouse);
let cable = document.getElementsByTagName("div");
console.log(cable);
let water = document.querySelector("#content");
console.log(water);
let queries = document.getElementsByClassName("p");
console.log(queries);